name: .NET Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore --configfile Nuget.config

    - name: Build
      run: dotnet build --nologo --no-restore --configuration Debug

    - name: Zip remaining files
      run: |
        Compress-Archive -Path ${{ env.SolutionName }}-${{ matrix.configuration }} -DestinationPath ${{ env.SolutionName }}-${{ matrix.configuration }}.zip
      # Upload artifact with github commit SHA
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.SolutionName }}-${{ matrix.configuration }}-${{ github.sha }}
        path: ${{ env.SolutionName }}-${{ matrix.configuration }}\
        if-no-files-found: error
